const mockEvents = {
"city": {
    "id": 1007700,
    "city": "München",
    "lat": 48.14,
    "lon": 11.58,
    "state": "",
    "country": "de",
    "zip": "meetup3",
    "member_count": 1257
},
"events" : [
    {
        "created": 1593357919000,
        "duration": 3600000,
        "id": "bknttrybckbkb",
        "name": "Outdoor und Online Training [Natural Movement]",
        "rsvp_limit": 7,
        "date_in_series_pattern": false,
        "status": "upcoming",
        "time": 1594139400000,
        "local_date": "2020-07-07",
        "local_time": "18:30",
        "rsvp_close_offset": "PT2H",
        "updated": 1593357919000,
        "utc_offset": 7200000,
        "waitlist_count": 0,
        "yes_rsvp_count": 2,
        "venue": {
        "id": 26215358,
        "name": "Westpark",
        "lat": 48.12034225463867,
        "lon": 11.511041641235352,
        "repinned": true,
        "address_1": "Specklinplatz",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
        },
        "is_online_event": false,
        "group": {
        "created": 1551533080000,
        "name": "MovNat München [Natural Movement Fitness]",
        "id": 31289377,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "MovNat-Munchen-Natural-Movement-Fitness",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
        },
        "link": "https://www.meetup.com/MovNat-Munchen-Natural-Movement-Fitness/events/bknttrybckbkb/",
        "description": "<p>----------------------- Natural Movement Fitness Training -----------------------<br/>Wir bieten Dienstags ein Live Online Training im Wechsel mit Workshops und Trainings im Westpark.</p> <p>Das erste Probetraining ist kostenlos.</p> <p>Bitte schreibt uns bei Interesse direkt an oder abonniert unseren Newsletter um wöchentlich die Termine, Treffpunkte und Zeiten zu bekommen.</p> <p>Wir freuen uns auf euch!</p> <p><a href=\"http://www.movnatmuenchen.de\" class=\"linkified\">http://www.movnatmuenchen.de</a> --- [masked]</p> ",
        "how_to_find_us": "Schreibe uns für den genauen Treffpunkt",
        "visibility": "public",
        "member_pay_fee": false
        },
        {
        "local_time": "18:30",
        "local_date": "2020-07-07",
        "link": "https://www.meetup.com/munich-english-yoga-meetup/events/hjsptrybckbkb/",
        "visibility": "public_limited",
        "group": {
        "created": 1562661524000,
        "name": "Munich English Yoga Meetup I Affordable | City center",
        "id": 32349747,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "munich-english-yoga-meetup",
        "who": "Munich Yogis",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
        },
        "waitlist_count": 0,
        "yes_rsvp_count": 1,
        "duration": 3600000,
        "time": 1594139400000,
        "utc_offset": 7200000,
        "name": "Outdoor Yoga Munich in English -  (book at englishyogameetup.com)",
        "id": "hjsptrybckbkb"
        },
        {
        "created": 1594022925000,
        "duration": 7200000,
        "id": "271746522",
        "name": "Yoga for joy of life and alignment + Picnic in the English Garden ",
        "date_in_series_pattern": false,
        "status": "upcoming",
        "time": 1594225800000,
        "local_date": "2020-07-08",
        "local_time": "18:30",
        "updated": 1594022925000,
        "utc_offset": 7200000,
        "waitlist_count": 0,
        "yes_rsvp_count": 3,
        "venue": {
        "id": 13736592,
        "name": "Odeonsplatz at the left lion in front of Feldherrnhalle",
        "lat": 48.14384460449219,
        "lon": 11.57824993133545,
        "repinned": true,
        "address_1": "Odeonsplatz",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
        },
        "is_online_event": false,
        "group": {
        "created": 1369987359000,
        "name": "Yoga in the English Garden + picnic",
        "id": 8719352,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Yoga-in-the-English-Garden-picnic",
        "who": "English garden picnic yogis",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
        },
        "link": "https://www.meetup.com/Yoga-in-the-English-Garden-picnic/events/271746522/",
        "description": "<p>this dynamic yogaset helps you to be aligned and to have a clear attitude and willpower. It relaxes and harmonizes our energies. This yoga is excellent for the soul, the back, the breath and the good mood. We go from the Odeonsplatz to a beautiful place in the English garden beside the Schwabing river and close to some trees. The exercises are quite simple, but intense. During the relaxation i play live on 6 singing bowls. After 90 minutes of yoga, relaxation and meditation we will have a picnic together.</p> <p>We meet at 18.30 and go 5 minutes later into the English Garden.</p> <p>* i will have some mats with me - please bring a mat, blanket or sheepskin</p> <p>* i will bring good vegetarian food - what kind of food do you like to bring ?</p> <p>* in the case of uncertain weather : please call me 0176/four four four eight eight six one one[masked] from 10.00 am , if the outdoor event can take place.</p> ",
        "how_to_find_us": "white cap+blue trolley",
        "visibility": "public",
        "member_pay_fee": false
        },
        {
        "created": 1588891812000,
        "duration": 3600000,
        "id": "xlmcsrybckbnb",
        "name": "GOA Yoga: Total Body Power Yoga - Day 5 | Yoga With Tim",
        "date_in_series_pattern": false,
        "status": "upcoming",
        "time": 1594396800000,
        "local_date": "2020-07-10",
        "local_time": "18:00",
        "updated": 1588891812000,
        "utc_offset": 7200000,
        "waitlist_count": 0,
        "yes_rsvp_count": 1,
        "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
        },
        "is_online_event": true,
        "group": {
        "created": 1447452736000,
        "name": "Great Outdoor Adventurers - DE",
        "id": 19119091,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "DE01GOA",
        "who": "Adventurists",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
        },
        "link": "https://www.meetup.com/DE01GOA/events/xlmcsrybckbnb/",
        "description": "<p>Join Tim for a yoga workout session every two weeks from Monday to Sunday.</p> <p>These sessions offer a strong full-body sequence designed to give you a great workout. We start with a dynamic flow to warm up the body, followed by a balanced mix of strengthening and lengthening, with a focus on developing core strength. Feel free to repeat the class should you need more practice before continuing with the next session.</p> <p>If you are new to yoga - you are welcome to join these yoga sessions. Great way to unwind after a days work - whether you work from home in front of your laptop or are on the front lines as an essential worker..</p> <p>From the comfort of your own home or the garden (with the best view from your yoga mat)</p> <p>🧘🏻Total Body Power Yoga Day 5<br/>🧘🏻<a href=\"https://youtu.be/xj1b7IbLZ2U\" class=\"embedded\">https://youtu.be/xj1b7IbLZ2U</a><br/>⏲️ This yoga duration lasts for 56mins.</p> <p>⏱ Event Time: Anytime is good time for a yoga session with Tim.</p> <p>🎟 Tickets: This is FREE online yoga session only.</p> <p>🖳 Smart TV/PC/Laptop/Smart Phone: Connect to the Media Channels via Youtube or Vimeo</p> <p>📸️ Instagram: @TimSenesiYoga Facebook: Tim Senesi Yoga</p> <p>#EuroHikerTraveller #GreatOutdoorAdventurers #GOA-Yoga</p> ",
        "visibility": "public",
        "member_pay_fee": false
        },
        {
        "created": 1593358152000,
        "duration": 3600000,
        "id": "vknttrybckblb",
        "name": "Outdoor Training [Natural Movement]",
        "rsvp_limit": 7,
        "date_in_series_pattern": false,
        "status": "upcoming",
        "time": 1594229400000,
        "local_date": "2020-07-08",
        "local_time": "19:30",
        "rsvp_close_offset": "PT3H",
        "updated": 1593358152000,
        "utc_offset": 7200000,
        "waitlist_count": 0,
        "yes_rsvp_count": 1,
        "venue": {
        "id": 26215366,
        "name": "Luitpold Park",
        "lat": 48.172027587890625,
        "lon": 11.56738567352295,
        "repinned": true,
        "address_1": "Brunnerstraße 2",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
        },
        "is_online_event": false,
        "group": {
        "created": 1551533080000,
        "name": "MovNat München [Natural Movement Fitness]",
        "id": 31289377,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "MovNat-Munchen-Natural-Movement-Fitness",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
        },
        "link": "https://www.meetup.com/MovNat-Munchen-Natural-Movement-Fitness/events/vknttrybckblb/",
        "description": "<p>Unser Mittwochstraining im Luitpoldpark</p> <p>Zweite Trainingseinheit 19:30 bis 20:30 Uhr</p> <p>Ein Probetraining ist kostenlos. Bitte kontaktiere uns auf jeden Fall vorher bis spätestens 16:30 Uhr am gleichen Tag per E-Mail wenn du kommen möchtest falls es einen spontanen Wechsel des Treffpunkts gibt.</p> <p>Wir freuen uns auf dich!</p> <p>Alle weiteren Trainings:<br/>5er-Karte: 70,-€ / 10er-Karte: 120,-€<br/>3-Monatskarte: 70,-€/Monat<br/>6- Monatskarte: 60,-€/Monat</p> <p><a href=\"http://www.movnatmuenchen.de\" class=\"linkified\">http://www.movnatmuenchen.de</a> --- [masked]</p> ",
        "how_to_find_us": "Schreibe uns für den genauen Treffpunkt",
        "visibility": "public",
        "member_pay_fee": false
        },
        {
        "local_time": "18:30",
        "local_date": "2020-07-08",
        "link": "https://www.meetup.com/munich-english-yoga-meetup/events/pffrsrybckblb/",
        "visibility": "public_limited",
        "group": {
        "created": 1562661524000,
        "name": "Munich English Yoga Meetup I Affordable | City center",
        "id": 32349747,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "munich-english-yoga-meetup",
        "who": "Munich Yogis",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
        },
        "waitlist_count": 0,
        "yes_rsvp_count": 1,
        "duration": 3600000,
        "time": 1594225800000,
        "utc_offset": 7200000,
        "name": "Online Yoga Flow x Home (5€, book at www.englishyogameetup.com)",
        "id": "pffrsrybckblb"
        },
        {
        "created": 1593097044000,
        "duration": 3600000,
        "id": "271519393",
        "name": "Sommer, Sonne und ... Segeln auf dem Mittelmeer",
        "date_in_series_pattern": false,
        "status": "upcoming",
        "time": 1595178000000,
        "local_date": "2020-07-19",
        "local_time": "19:00",
        "updated": 1593865039000,
        "utc_offset": 7200000,
        "waitlist_count": 0,
        "yes_rsvp_count": 2,
        "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
        },
        "is_online_event": true,
        "group": {
        "created": 1520018472000,
        "name": "München Segeln Meetup",
        "id": 27702739,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Munchen-Segeln-Meetup",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
        },
        "link": "https://www.meetup.com/Munchen-Segeln-Meetup/events/271519393/",
        "description": "<p>Was diese Saison mit der Segelei auf dem Mittelmeer gehen könnte und ich freue mich auf potentielle Mitstreiter!</p> <p>(1) Im September von Istrien / Kroatien auf einer kleinen Segelyacht ablegen und die Inselwelt der Kvarner Bucht entdecken; mögliche Termine wären spontan 25.7.-1.8. oder im ;</p> <p>(2) Rund um den halben Peloponnes, von Lefkada aus dem Ionischen Meer nach Athen, 2 Wochen auf einer 40er Segelyacht (3 Kabinen) im Oktober (Details auf Anfrage);</p> <p>Mitanpacken ist erwünscht, Segelkenntnisse nicht unbedingt erforderlich, ausprobieren also möglich!<br/>Und das ganze ist natürlich keine kommerzielle Veranstaltung, wir teilen die Unkosten (Charter, Gebühren, Bordkasse usw.) untereinander auf, je nachdem wieviele wir werden (erfahrungsgemäs ca. 500.- + Bordkasse)</p> <p>Bei Fragen, Interesse gerne PN an mich bzw. in die Online-Konferenz einwählen (Link folgt noch)</p> <p>Update: neuer Termin für ein Treffen in einem Biergarten oder bei Regen per Online-Event;<br/>Isaac kennt sich bereits aus ;)</p> ",
        "visibility": "public",
        "member_pay_fee": false
        },
        {
        "created": 1589308091000,
        "duration": 10800000,
        "id": "cmxzsrybcjbzb",
        "name": "Friday Beergarden (& pub)",
        "rsvp_limit": 40,
        "date_in_series_pattern": false,
        "status": "upcoming",
        "time": 1594745100000,
        "local_date": "2020-07-14",
        "local_time": "18:45",
        "updated": 1591796684000,
        "utc_offset": 7200000,
        "waitlist_count": 0,
        "yes_rsvp_count": 7,
        "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
        },
        "is_online_event": true,
        "group": {
        "created": 1210500936000,
        "name": "Munich Stammtisch",
        "id": 1145675,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "MunichStammtisch",
        "who": "Munich Stammtischers",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
        },
        "link": "https://www.meetup.com/MunichStammtisch/events/cmxzsrybcjbzb/",
        "description": "<p>JOIN 30-50 of us for beer, cocktails, food and fun, in beergardens and pubs all round Munich, every Friday of the year! We are only indoors if it's cold or wet.</p> <p>Until it's safe again, we're on video chat each week.<br/>Every Friday Video chat with Jitsi from 7pm. Just click our link to join.</p> ",
        "how_to_find_us": "https://meet.jit.si/FridayBeergarden",
        "visibility": "public",
        "member_pay_fee": false
        }
]
}
export {mockEvents}